AVIAONE-validator-info.md for AtomOne
atomone-hub/atomone-validator-community pull request #47
Opened 2024-11-06 03:12 UTC by AviaOne

Add Validator AviaOne to the list of AtomOne

2024-11-21 19:46 UTC, Ticojohnny commented
Hi @AviaOne  - Thank you for providing the details. Can you provide the country where the entity is registered please.

2024-11-22 01:40 UTC, AviaOne commented
Hi,
Do you ask the same thing to validators who have already obtained the validator role without this form ?

We are on 15 mainnets since 3 year, located in Thailand.

If you have any doubts about our reliability or our skills, we are at your disposal to give you more details.

Best Regards

2024-11-22 01:50 UTC, AviaOne reviewed
Add region in this file

2024-12-10 02:37 UTC, AviaOne commented
Still here ?

2026-07-31 16:39 UTC, tbruyelle requested changes
Thanks for the submission — it can't be verified as it stands.

**The transaction exists, but its memo is empty.**

`74D0D1052E9F7150D3FE431886D7759C3DE73C34B42F5FBAF4ECC67744909EC0`

The memo is the whole mechanism — it is what binds specific Discord accounts to your validator key. Your row lists `@aviaone and @community_aviaone`, but nothing on chain records that.

**To fix:** send 0.01 ATONE from your validator's own account to any ATONE address with `@aviaone and @community_aviaone` in the **memo**, then update the row with that hash.

```
atomoned tx bank send <your-validator-account> <any-atone-address> 10000uatone \
  --note "<your discord handles>" --chain-id atomone-1
```
---

`validator-info.md` changed after you opened this: #170 added every verified entry, so this branch now conflicts with `main`. Update your branch and add your row at the end of the table.

The three checks every submission has to pass, and the full audit of all 128 submissions, are in #168.

2026-08-01 10:07 UTC, AviaOne commented
Updated.

- Restored the shared `validator-info.md` (the PR no longer renames it) and added AviaOne as a single row.
- New TX with the Discord handles in the memo, sent from the validator's own account:
  190107B99A228CC167C866E48EE4C7143BD613FE138736907127D9EF5C9D3413
  memo: @ aviaone and @community_aviaone

This addresses the empty-memo and renamed-file findings in #168.

2026-08-01 12:03 UTC, tbruyelle approved these changes

2026-08-01 12:03 UTC, merged