Update validator-info.md Oneiric Stake
atomone-hub/atomone-validator-community pull request #54
Opened 2024-11-06 13:01 UTC by cougarmaster

2026-07-31 16:39 UTC, tbruyelle requested changes
Thanks for the submission — it can't be verified as it stands.

**The memo does not contain any of the Discord handles in your row.**

- memo: `TX From Oneiric Stake`
- Discord handles column: `cougarmaster`

The memo has to name the handles themselves. A validator name, a note, or an explorer label does not work — the point is to prove those specific Discord accounts belong to this validator.

**To fix:** re-send with `cougarmaster` in the memo and update the hash.

```
atomoned tx bank send <your-validator-account> <any-atone-address> 10000uatone \
  --note "<your discord handles>" --chain-id atomone-1
```
---

`validator-info.md` changed after you opened this: #170 added every verified entry, so this branch now conflicts with `main`. Update your branch and add your row at the end of the table.

The three checks every submission has to pass, and the full audit of all 128 submissions, are in #168.

2026-07-31 18:56 UTC, cougarmaster commented
I have updated the file please check

2026-08-01 12:11 UTC, tbruyelle commented
I can't find this hash 5780D587C593493290DAB52EA56BDE3F3BB90519CEE39DC33ED5BB81A31AF0A4 on mainnet.

2026-08-01 12:18 UTC, cougarmaster commented
can I make another transaction and post here?


On Sat, Aug 1, 2026 at 8:11 PM Thomas ***@***.***> wrote:

> *tbruyelle* left a comment (atomone-hub/atomone-validator-community#54)
> <https://github.com/atomone-hub/atomone-validator-community/pull/54#issuecomment-5151361687>
>
> I can't find this hash
> 5780D587C593493290DAB52EA56BDE3F3BB90519CEE39DC33ED5BB81A31AF0A4 on mainnet.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/atomone-hub/atomone-validator-community/pull/54?email_source=notifications&email_token=A3635DM7ZOBU7NZ4BZY5HDT5HXM6XA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTKMJVGEZTMMJWHA32M4TFMFZW63VGMF2XI2DPOKSWK5TFNZ2KYZTPN52GK4S7MNWGSY3L#issuecomment-5151361687>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3635DLMQ7F2FTHX5R5E7FD5HXM6XAVCNFSNUABFKJSXA33TNF2G64TZHM4DKOJTGYYTIOJQHNEXG43VMU5TENRTHAYDGMBYHEZ2C5QC>
> .
> Triage notifications, keep track of coding agent tasks and review pull
> requests on the go with GitHub Mobile for iOS
> <https://github.com/notifications/mobile/ios/A3635DO2OMUNSWMT5UEA3UT5HXM6XA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTKMJVGEZTMMJWHA32M4TFMFZW63VGMF2XI2DPOKSWK5TFNZ2KUZTPN52GK4S7NFXXG>
> and Android
> <https://github.com/notifications/mobile/android/A3635DNHOUEIIUMCV2ITUS35HXM6XA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTKMJVGEZTMMJWHA32M4TFMFZW63VGMF2XI2DPOKSWK5TFNZ2K4ZTPN52GK4S7MFXGI4TPNFSA>.
> Download it today!
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2026-08-01 12:19 UTC, tbruyelle commented
> can I make another transaction and post here?

Yes

2026-08-01 12:25 UTC, cougarmaster commented
Sorry I made mistake I need to set my node I am sorry I will update asap


On Sat, Aug 1, 2026 at 8:16 PM Cougar Master ***@***.***> wrote:

> can I make another transaction and post here?
>
>
> On Sat, Aug 1, 2026 at 8:11 PM Thomas ***@***.***> wrote:
>
>> *tbruyelle* left a comment (atomone-hub/atomone-validator-community#54)
>> <https://github.com/atomone-hub/atomone-validator-community/pull/54#issuecomment-5151361687>
>>
>> I can't find this hash
>> 5780D587C593493290DAB52EA56BDE3F3BB90519CEE39DC33ED5BB81A31AF0A4 on mainnet.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/atomone-hub/atomone-validator-community/pull/54?email_source=notifications&email_token=A3635DM7ZOBU7NZ4BZY5HDT5HXM6XA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTKMJVGEZTMMJWHA32M4TFMFZW63VGMF2XI2DPOKSWK5TFNZ2KYZTPN52GK4S7MNWGSY3L#issuecomment-5151361687>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/A3635DLMQ7F2FTHX5R5E7FD5HXM6XAVCNFSNUABFKJSXA33TNF2G64TZHM4DKOJTGYYTIOJQHNEXG43VMU5TENRTHAYDGMBYHEZ2C5QC>
>> .
>> Triage notifications, keep track of coding agent tasks and review pull
>> requests on the go with GitHub Mobile for iOS
>> <https://github.com/notifications/mobile/ios/A3635DO2OMUNSWMT5UEA3UT5HXM6XA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTKMJVGEZTMMJWHA32M4TFMFZW63VGMF2XI2DPOKSWK5TFNZ2KUZTPN52GK4S7NFXXG>
>> and Android
>> <https://github.com/notifications/mobile/android/A3635DNHOUEIIUMCV2ITUS35HXM6XA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTKMJVGEZTMMJWHA32M4TFMFZW63VGMF2XI2DPOKSWK5TFNZ2K4ZTPN52GK4S7MFXGI4TPNFSA>.
>> Download it today!
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2026-08-01 12:42 UTC, cougarmaster commented
A48C575037781F10242C9FA4034D251EF1D33F2ABC39DD9141F2DA5A44A56A42
On Sat, Aug 1, 2026 at 8:24 PM Cougar Master ***@***.***> wrote:

> Sorry I made mistake I need to set my node I am sorry I will update asap
>
>
> On Sat, Aug 1, 2026 at 8:16 PM Cougar Master ***@***.***> wrote:
>
>> can I make another transaction and post here?
>>
>>
>> On Sat, Aug 1, 2026 at 8:11 PM Thomas ***@***.***> wrote:
>>
>>> *tbruyelle* left a comment (atomone-hub/atomone-validator-community#54)
>>> <https://github.com/atomone-hub/atomone-validator-community/pull/54#issuecomment-5151361687>
>>>
>>> I can't find this hash
>>> 5780D587C593493290DAB52EA56BDE3F3BB90519CEE39DC33ED5BB81A31AF0A4 on mainnet.
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/atomone-hub/atomone-validator-community/pull/54?email_source=notifications&email_token=A3635DM7ZOBU7NZ4BZY5HDT5HXM6XA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTKMJVGEZTMMJWHA32M4TFMFZW63VGMF2XI2DPOKSWK5TFNZ2KYZTPN52GK4S7MNWGSY3L#issuecomment-5151361687>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/A3635DLMQ7F2FTHX5R5E7FD5HXM6XAVCNFSNUABFKJSXA33TNF2G64TZHM4DKOJTGYYTIOJQHNEXG43VMU5TENRTHAYDGMBYHEZ2C5QC>
>>> .
>>> Triage notifications, keep track of coding agent tasks and review pull
>>> requests on the go with GitHub Mobile for iOS
>>> <https://github.com/notifications/mobile/ios/A3635DO2OMUNSWMT5UEA3UT5HXM6XA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTKMJVGEZTMMJWHA32M4TFMFZW63VGMF2XI2DPOKSWK5TFNZ2KUZTPN52GK4S7NFXXG>
>>> and Android
>>> <https://github.com/notifications/mobile/android/A3635DNHOUEIIUMCV2ITUS35HXM6XA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTKMJVGEZTMMJWHA32M4TFMFZW63VGMF2XI2DPOKSWK5TFNZ2K4ZTPN52GK4S7MFXGI4TPNFSA>.
>>> Download it today!
>>> You are receiving this because you authored the thread.Message ID:
>>> ***@***.***>
>>>
>>

2026-08-01 12:48 UTC, cougarmaster commented
I updated sorry for the mistake I forgot to put in the fee so it didn't go through.

2026-08-01 14:55 UTC, tbruyelle approved these changes
Had to fix your commit since it removed some other validators...

2026-08-01 14:55 UTC, merged

2026-08-01 14:57 UTC, cougarmaster commented
Thanks sorry about the mess up

On Sat, Aug 1, 2026 at 10:56 PM Thomas ***@***.***> wrote:

> Merged #54
> <https://github.com/atomone-hub/atomone-validator-community/pull/54> into
> main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/atomone-hub/atomone-validator-community/pull/54?email_source=notifications&email_token=A3635DL5V7BG4PF3DXBMVDD5HYAIRA5CNFSNUABQM5UWIORPF5TWS5BNNB2WEL2JONZXKZKFOZSW45CON52GSZTJMNQXI2LPNYXTEOBYGIYDINZQGUZDNJTSMVQXG33OUZQXK5DIN5ZKKZLWMVXHJLDGN5XXIZLSL5RWY2LDNM#event-28820470526>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3635DIFWV6R2JV7RGHFURD5HYAIRAVCNFSNUABFKJSXA33TNF2G64TZHM4DKOJTGYYTIOJQHNEXG43VMU5TENRTHAYDGMBYHEZ2C5QC>
> .
> Triage notifications, keep track of coding agent tasks and review pull
> requests on the go with GitHub Mobile for iOS
> <https://github.com/notifications/mobile/ios/A3635DMHSRWDT3QAHINDTHL5HYAIRA5CNFSNUABQM5UWIORPF5TWS5BNNB2WEL2JONZXKZKFOZSW45CON52GSZTJMNQXI2LPNYXTEOBYGIYDINZQGUZDNJTSMVQXG33OUZQXK5DIN5ZKKZLWMVXHJKTGN5XXIZLSL5UW64Y>
> and Android
> <https://github.com/notifications/mobile/android/A3635DMSCM5DUIGH4I4ULXT5HYAIRA5CNFSNUABQM5UWIORPF5TWS5BNNB2WEL2JONZXKZKFOZSW45CON52GSZTJMNQXI2LPNYXTEOBYGIYDINZQGUZDNJTSMVQXG33OUZQXK5DIN5ZKKZLWMVXHJLTGN5XXIZLSL5QW4ZDSN5UWI>.
> Download it today!
> You are receiving this because you authored the thread.Message ID:
> <atomone-hub/atomone-validator-community/pull/54/issue_event/28820470526@
> github.com>
>