Add Cogwheel to validator-info.md
atomone-hub/atomone-validator-community pull request #67
Opened 2024-11-10 10:24 UTC by Kamikaza731

2026-07-31 16:40 UTC, tbruyelle requested changes
Thanks for the submission — it can't be verified as it stands.

**The memo proves only some of the Discord handles in your row.**

- memo: `Cogwheel ⚙️`
- row lists: `Kamikaza 731 | Cogwheel ⚙️`

- proven: `Cogwheel`
- **not proven: `Kamikaza`, `731`**

The unproven handles cannot be given the validator role on this evidence.

**To fix:** either re-send with every handle in the memo, or remove the unproven ones from the row.

```
atomoned tx bank send <your-validator-account> <any-atone-address> 10000uatone \
  --note "<your discord handles>" --chain-id atomone-1
```
---

`validator-info.md` changed after you opened this: #170 added every verified entry, so this branch now conflicts with `main`. Update your branch and add your row at the end of the table.

The three checks every submission has to pass, and the full audit of all 128 submissions, are in #168.

2026-07-31 19:45 UTC, nman98 commented
@tbruyelle this is actually written correctly according to the Markdown rules. The discord name is "Kamikaza731| Cogwheel ⚙️" This is a whole name, not a list in any way. So in the markdown it was written like this Kamikaza731 \| Cogwheel so when you look at the table it is represented correctly.

Example:

|Broken Table | Discord Users |
| --- | --- |
| Kamikaza731 | Cogwheel ⚙️ |

Or another ( view as raw text ):

|Broken Table | Discord Users |
| --- | --- |
| SomeInsert | Kamikaza731 | Cogwheel  ⚙️|

As I wrote it initially:

| Working table | Discord Users |
| --- | --- |
| SomeInsert | Kamikaza731 \| Cogwheel ⚙️ |

So for this to be parsed by markdown correctly I need to write is like this  "Kamikaza731 \| Cogwheel ⚙️". I can alter it but then markdown will not parse this data correctly.

2026-08-01 12:17 UTC, tbruyelle commented
"Kamikaza731| Cogwheel ⚙️" is your full discord name, and your handle is `kamikaza731`. The column and memo requires handles, they are more uniques than names and references better the discord user. Please update accordingly.

2026-08-01 13:11 UTC, nman98 commented
Understood, the new entry now stores discord handle instead of the discord name, I also made a new transaction which holds memo "kamikaza731".

2026-08-01 14:48 UTC, tbruyelle approved these changes

2026-08-01 14:49 UTC, tbruyelle commented
I cant fix the conflicts myself (looks like you protected your branch). Fix them or give me permission to do it.

2026-08-02 16:34 UTC, tbruyelle approved these changes

2026-08-02 16:34 UTC, merged