Update validator-info.md Add NODERS
atomone-hub/atomone-validator-community pull request #69
Opened 2024-11-12 14:57 UTC by nodersteam

Add noders info

2024-11-13 15:12 UTC, VT-Cosmos commented
Hi @nodersteam - Thank you for submitting the information. Can you provide the country please.

2024-11-16 12:52 UTC, nodersteam commented
> Hi @nodersteam - Thank you for submitting the information. Can you provide the country please.

Hello! Sure, added
Thx a lot

2024-11-18 11:51 UTC, VT-Cosmos commented
Thank you

2026-07-31 16:40 UTC, tbruyelle requested changes
Thanks for the submission — it can't be verified as it stands.

**The memo does not contain any of the Discord handles in your row.**

- memo: `ping.pub`
- Discord handles column: `nodersseptima`

The memo has to name the handles themselves. A validator name, a note, or an explorer label does not work — the point is to prove those specific Discord accounts belong to this validator.

**To fix:** re-send with `nodersseptima` in the memo and update the hash.

```
atomoned tx bank send <your-validator-account> <any-atone-address> 10000uatone \
  --note "<your discord handles>" --chain-id atomone-1
```

**Also: the transaction was not signed by your validator's account.**

- signer: `atone1wm4026rxqcrkh09k806m6y4lys942etxet6kda`
- [NODERS] account: `atone1f2r68y2htcmp4rfe2wfn9f3nvzh9xsq9xj8yw6`

That account has no delegation to your validator, so there is nothing linking it to you on chain.

The transfer has to come **from the validator account itself** (`atone1f2r68y2htcmp4rfe2wfn9f3nvzh9xsq9xj8yw6`), since that is what proves the submission comes from the operator and not from someone who merely knows the moniker.
---

`validator-info.md` changed after you opened this: #170 added every verified entry, so this branch now conflicts with `main`. Update your branch and add your row at the end of the table.

The three checks every submission has to pass, and the full audit of all 128 submissions, are in #168.

2026-08-27 12:23 UTC, closed without merging