Update tRDM | Nodera validator-info.md
atomone-hub/atomone-validator-community pull request #73
Opened 2024-11-13 19:30 UTC by terdim28

2024-11-14 00:33 UTC, fivetech-validator requested changes
This is a form intended to compile all of the information available from the current and future AtomOne validators as well as to verify AtomOne validators with their signing key so that their role in the AtomOne (Unofficial) Discord channel will be validated. 

In order to verify the team members of your validator, please send a 0.01 ATONE transaction from your AtomOne validator account with the Discord handles of those from your team you would like to represent your validator in an official capacity on the AtomOne (Unofficial) Discord channel, and be given the official "validator" role ( the Discord handles will be written in the memo field of the transaction). The transfer can be done to any existing ATONE address, with the requirement that the TX Hash link ( transaction hash link) needs to be provided to this form as to match the identity of your validator to the team members working for your validator.


| Name of Validator (name and moniker used for the AtomOne chain)  | Validator Website | Validator Twitter Page  | Region or Country where your validator operates  | Validator Team's GitHub handle (Organization) or individual GitHub handles (list all those involved with your Validator that will be participating in AtomOne activities)  | Validator Contact E-mail (Organization) or individual E-mail addresses  (list all those involved with your Validator that will be participating in AtomOne activities)  | Validator Team's Discord handles  (list all those involved with your Validator that will be participating in AtomOne activities)  | Transaction Hash link (TX Hash link) sent to any ATONE address to prove affiliation of discord users with your validator.  |
|-----------------------------------------------------------------|-------------------|---|---|---|---|---|---|
|---|---|---|---|---|---|---|---|
| Validator Name  | Validator Website | Validator Twitter Page | Region | GitHub Handles | E-mails | Discord Handles | Tx Hash |
|  FIVETECH | https://explorer.fivetech.pro  | https://x.com/phamvannamdc  |  VIET NAM | https://github.com/fivetech-validator  | phamvannamdc@gmail.com  | FIVETECH  | D92EB2E2C2E51F00F75C066771B48F93DD367E48E61D21344DFDFC925681A14F  |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |

2024-11-18 11:46 UTC, VT-Cosmos commented
Hi @terdim28 - Thank you for providing the details. Can you provide the country where the validator is registered please.

2024-11-18 16:54 UTC, terdim28 commented
> Hi @terdim28 - Thank you for providing the details. Can you provide the country where the validator is registered please.

Hi, @VT-Cosmos, PR updated

2026-07-31 16:27 UTC, tbruyelle commented
Landed in `main` via #170 — **tRDM I Nodera** is now in `validator-info.md`.

Verified before merging:

- the TX hash exists on `atomone-1`
- the memo lists the Discord handles from your row (`trdm`)
- the TX was signed by the validator's **own account** — the signing address, re-encoded as `atonevaloper…`, matches the operator address

Closing this PR because the change is already in `main`. It could not be merged directly: every submission rewrote the *same* placeholder row, so 64 of the 66 open PRs reported `CONFLICTING` and no merge order resolved it — the rows were landed together instead, so nobody had to rebase.

Full audit in #168. Thanks for submitting!

2026-07-31 16:27 UTC, closed without merging